language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
# command to install dependencies
install:
    - travis_retry pip install -r dev-requirements.txt
    - travis_retry pip install coveralls
# use new travis-ci container-based infrastructure
sudo: false
# command to run tests
script: nosetests
# command to run after tests
after_success:
    - coveralls
